---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-finalizer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-finalizer-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-finalizer-role-binding
subjects:
  - kind: ServiceAccount
    name: namespace-finalizer
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-finalizer-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-finalizer
  namespace: kube-system
  labels:
    app: namespace-finalizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-finalizer
  template:
    metadata:
      labels:
        app: namespace-finalizer
    spec:
      serviceAccountName: namespace-finalizer
      containers:
        - name: namespace-finalizer
          image: registry.example.com/namespace-finalizer:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
